name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - Docs/**
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  deploy:
    name: Deploy Docs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: main

      - uses: actions/checkout@v3
        with:
          path: gh-pages
          ref: gh-pages

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: main/Docs/package-lock.json

      - name: Install dependencies
        working-directory: main/Docs
        run: npm ci
      - name: Build website
        working-directory: main/Docs
        run: npm run build

      - name: Copy build files
        run: |
          rsync -a --exclude=".git/" --delete main/Docs/build/ gh-pages

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          path: gh-pages
          title: Update Docs
          base: gh-pages
